### ISSUE TITLE
TypeError - _aaronhayes_react_use_hubspot_form__WEBPACK_IMPORTED_MODULE_3___default(...) is not a function

### ISSUE THREAD

**Issue by kb1995** [aaronhayes/react-use-hubspot-form#24]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Hey, thanks a lot again for making this library. I'm just in the process of integrating it, but I got an error

My component looks like this:

```
import React from "react";
import useHubspotForm from "@aaronhayes/react-use-hubspot-form";

const HubspotForm = ({ slice }) => {
  const { loaded, error, formCreated } = useHubspotForm({
    portalId: "XXX-XXX",
    formId: "XXXX-XXXX-XXXX-XXX",
    target: "#hubspot-form",
  });
  return (
    <section>
      <div id="hubspot-form"></div>
    </section>
  );
};
export default HubspotForm;

```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

```
TypeError: _aaronhayes_react_use_hubspot_form__WEBPACK_IMPORTED_MODULE_3___default(...) is not a function
    at HubspotForm (webpack-internal:///./slices/HubspotForm/index.js:23:80)
    at processChild (/Users/kris/Documents/code/freelance/miso3/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/kris/Documents/code/freelance/miso3/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/kris/Documents/code/freelance/miso3/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/kris/Documents/code/freelance/miso3/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/kris/Documents/code/freelance/miso3/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/kris/Documents/code/freelance/miso3/node_modules/next/dist/next-server/server/render.js:53:854)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:211:19)
    at Function.getInitialProps (webpack-internal:///./pages/_document.tsx:27:85)
    at loadGetInitialProps (/Users/kris/Documents/code/freelance/miso3/node_modules/next/dist/next-server/lib/utils.js:5:101)
    ```

I have this library integrated in another project and there it works pretty well.

My React version of my current project is `17.0.2`.

**Comment by aaronhayes** [comment]
Hi @kb1995 , I think you just need to wrap the import in braces. i.e. 

`import { useHubspotForm } from '@aaronhayes/react-use-hubspot-form';`

instead of `import useHubspotForm from '@aaronhayes/react-use-hubspot-form';`

**Comment by kb1995** [comment]
@aaronhayes Arh such an obvious error - I just copied the component from my previous project which was on an older version of the library

That's a lesson not to do coding at midnight :D
